services:
  bootstrap:
    build: .
    image: p2p/main
    container_name: bootstrap
    command: python bootstrap_server.py
    networks:
      p2p-net:
        ipv4_address: 172.18.0.10  # Fester Anker / DNS-Seed

  peer1:
    build: .
    image: p2p/main
    container_name: peer1
    command: python publishSomePeerIPs.py
    networks:
      p2p-net:
        ipv4_address: 172.18.0.2  # Fester Peer für deterministische Tests, wird vom bootstrap-Server als bekanntes Peer veröffentlicht

  peer2:
    build: .
    image: p2p/main
    container_name: peer2
    command: python publishSomePeerIPs.py
    networks:
      p2p-net:
        # Keine ipv4_address -> Docker zieht sich automatisch die nächste freie IP (z.B. 172.18.0.3)

networks:
  p2p-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16