apiVersion: v1
kind: Namespace
metadata:
  name: p2p-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: p2p-service
  namespace: p2p-namespace
  labels:
    app: p2p
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
  selector:
    app: p2p
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: p2p-statefulSet
  namespace: p2p-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: p2p
  serviceName: "p2p-service"
  template:
    metadata:
      labels:
        app: p2p
    spec:
      containers:
      - image: ghcr.io/ateachment/p2p:main
        imagePullPolicy: "Always"   # can result in too much traffic -> better versioning of images later
        name: p2p-container
        ports:
        - containerPort: 80
      
