---
apiVersion: v1
kind: Service
metadata:
  name: p2p-service
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: p2p
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2p-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: p2p
  template:
    metadata:
      labels:
        app: p2p
    spec:
      containers:
      - image: ghcr.io/ateachment/p2p:main
        name: p2p-container
        ports:
        - containerPort: 8080
      hostname: p2p-pod
      subdomain: p2p-service
